name: CI/CD

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: admin


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-test-package:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Apply schema to PostgreSQL database
        run: |
          PGPASSWORD=admin psql -h localhost -U postgres -d postgres -f src/main/resources/schema.sql

      - name: Build and test with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare JAR for upload
        run: mkdir build && cp target/*.jar build

      - name: Upload resulting JAR
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t sulcer/bicycle-sharing-user-service .

      - name: Push Docker image
        run: docker push sulcer/bicycle-sharing-user-service